name: Delete old package
on:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/delete-package-versions@v4
        with: 
          package-name: 'metacubexd'
          package-type: 'container'
          min-versions-to-keep: 3
          delete-only-untagged-versions: 'true'

